import type { Metadata } from "next";
import type { Viewport } from 'next'
import { Nunito } from "next/font/google";
import "./globals.css";

import AuthSessionProvider from "@/components/AuthSessionProvider";
import { getServerSession } from "next-auth";
import authOptions from "@/app/api/auth/[...nextauth]/authOptions";
import StatusBar from "@/components/ui/StatusBar";

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Hackster",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" data-theme="synthwave">
      <AuthSessionProvider session={session}>
        <body className={nunito.className}>
          <StatusBar/>
          <div className="flex h-screen justify-center items-center px-6 py-10">
            {children}
          </div>
        </body>
      </AuthSessionProvider>
    </html>
  );
}
